### ISSUE TITLE
Misusing nice command in  run-single-process.sh resulting in low piority

### ISSUE THREAD

**Issue by manwantnosmoke** [ZettaScaleLabs/rust-async-net-eval#2]
Hi, really like the post, and was looking to see the updated tokio results.
running the rest locally i noticed the tested binaries ran with nice +10 instead of -10,
this is due to not putting the -n flag in the nice command.

**Comment by gabrik** [comment]
Thanks for spotting this, going to fix and re-run the tests.

**Comment by gabrik** [comment]
Fixed in https://github.com/ZettaScaleLabs/rust-async-net-eval/commit/675e4730c3d1500eab154d858b94ca8906ff4b34
